// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLyRUnNXlaEax7yuNHM-la6ev2xSfcPms',
    appId: '1:585974791785:web:a2bc4ca13c8d34f234ecf8',
    messagingSenderId: '585974791785',
    projectId: 'intern-1d35d',
    authDomain: 'intern-1d35d.firebaseapp.com',
    storageBucket: 'intern-1d35d.firebasestorage.app',
    measurementId: 'G-81RYNLH0HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMC8c26ZIUCPy_BcRCRM_pDL1zzQyte9c',
    appId: '1:585974791785:android:f998d4ffeeb3009734ecf8',
    messagingSenderId: '585974791785',
    projectId: 'intern-1d35d',
    storageBucket: 'intern-1d35d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBST19fG5KutbT_fvhnBJxXIgK0nhsKrTc',
    appId: '1:585974791785:ios:6318b2170cac2e1b34ecf8',
    messagingSenderId: '585974791785',
    projectId: 'intern-1d35d',
    storageBucket: 'intern-1d35d.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBST19fG5KutbT_fvhnBJxXIgK0nhsKrTc',
    appId: '1:585974791785:ios:6318b2170cac2e1b34ecf8',
    messagingSenderId: '585974791785',
    projectId: 'intern-1d35d',
    storageBucket: 'intern-1d35d.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLyRUnNXlaEax7yuNHM-la6ev2xSfcPms',
    appId: '1:585974791785:web:ac045be4da3e550234ecf8',
    messagingSenderId: '585974791785',
    projectId: 'intern-1d35d',
    authDomain: 'intern-1d35d.firebaseapp.com',
    storageBucket: 'intern-1d35d.firebasestorage.app',
    measurementId: 'G-7PBXTBKSKW',
  );
}
